### ISSUE TITLE
RuntimeError: merge_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered

### ISSUE THREAD

**Issue by wanghq-thu** [rhett-chen/graspness_implementation#40]
I have encountered the following problem. Has anyone encountered this problem?
TITAN Xp 12G

(py37-mink) [wanghq@gpu31 graspness_implementation]$ sh command_train.sh 
/home/Wanghq/anaconda3/envs/py37-mink/lib/python3.7/site-packages/MinkowskiEngine-0.5.4-py3.7-linux-x86_64.egg/MinkowskiEngine/__init__.py:42: UserWarning: The environment variable `OMP_NUM_THREADS` not set. MinkowskiEngine will automatically set `OMP_NUM_THREADS=16`. If you want to set `OMP_NUM_THREADS` manually, please export it on the command line before running a python script. e.g. `export OMP_NUM_THREADS=12; python your_program.py`. It is recommended to set it below 24.
  "It is recommended to set it below 24.",
Loading grasping labels...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 88/88 [00:20<00:00,  4.21it/s]
Loading data path and collision labels...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:20<00:00,  4.79it/s]
train dataset length:  25600
train dataloader length:  6400
**** EPOCH 000 ****
Current learning rate: 0.001000
2024-07-18 14:07:59.012848
/home/Wanghq/anaconda3/envs/py37-mink/lib/python3.7/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448265233/work/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Traceback (most recent call last):
  File "train.py", line 148, in <module>
    train(start_epoch)
  File "train.py", line 140, in train
    train_one_epoch()
  File "train.py", line 111, in train_one_epoch
    loss.backward()
  File "/home/Wanghq/anaconda3/envs/py37-mink/lib/python3.7/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/Wanghq/anaconda3/envs/py37-mink/lib/python3.7/site-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: merge_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered

![image](https://github.com/user-attachments/assets/5de3d52d-2246-48ff-948e-b57e4f0900d2)

**Comment by wanghq-thu** [comment]
I have found the source of the problem. It's an issue with the Minkowski Engine library version, version 0.5.4. is not working and the latest version needs to be installed. I found the answer on the Minkowski Engine issue. 
[merge_sort: failed to synchronize: cudaErrorIllegalAddress with TensorField during training on some ScanNet scans #395](https://github.com/NVIDIA/MinkowskiEngine/issues/395)
